# # Project Information
site_name: XoXo Docs
site_url: https://docs.xoxoharsh.in/
site_author: Harsh Sharma
site_description: >-
  A personal documentation repository featuring concise notes, guides, troubleshooting logs, and verified code snippets for efficient full-stack development, tailored for personal reference and skill growth.

# Repository
repo_name: harshsharma20503/docs
repo_url: https://github.com/harshsharma20503/docs

# Copyright
copyright: Copyright &copy; 2024 Harsh Sharma

# Theme
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple # suggested deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  font:
    text: Inter
    code: JetBrains Mono
  language: en
extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harshsharma20503
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/harshsharma20503/
      name: LinkedIn
  generator: false
  meta_tags:
    - name: keywords
      content: documentation, programming, code snippets
    - name: author
      content: Harsh Sharma
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
